# Site settings
title: Vortexel
motto: Done with a pun
email: info@vortexel.com
description: > # this means to ignore newlines until "baseurl:"
  This website belongs to Vortan / BinderNews. There are many like it,
  but this one is mine.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vortexel.com" # the base hostname & protocol for your site
twitter_username: bindernews
github_username:  Bindernews

# Build settings
markdown: kramdown
